In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
import string

In [2]:
# https://stackoverflow.com/questions/11707586/how-do-i-expand-the-output-display-to-see-more-columns-of-a-pandas-dataframe
pd.options.display.max_colwidth = 800

In [3]:
geolocater = Nominatim(user_agent = "mapping store locations to county")

In [12]:
cabelas = pd.read_csv("data/cabelas_location.csv", header=None).rename(columns={0: "store_location"})
cinemarks = pd.read_csv("data/cinemark_location.csv", header=None).rename(columns={0: "store_location"})
nordstroms = pd.read_csv("data/nordstrom_location.csv", header=None).rename(columns={0: "store_location"})
trader_joes = pd.read_csv("data/trader_joes_location.csv", header=None).rename(columns={0: "store_location"})

In [125]:
def get_county(df, store_name):
    counties = []
    for i in range(len(df['store_location'])):
        address = df['store_location'][i]
        if (store_name =='nordstroms' or store_name=='trader_joes') and ('10003' in address or '01803' in address):
            counties.append(None)
            continue
        loc = geolocater.geocode(address)
        found_space = True 
        if not loc:
            if " " in address:
                address = address.split(" ", 1)[1]
                loc = geolocater.geocode(address)
        while not loc:
            if ", " in address:
                address = address.split(" ", 1)[1]
                loc = geolocater.geocode(address)
    #             if not loc:
    #                 print(address)
            else:
                found_space = False
                break
        if found_space:
            loc_sections = loc.address.split(", ")
            try:
                counties.append([l for l in loc_sections if ((" County" in l) or (" Parish" in l))][0])
            except:
                counties.append(None)
                print(loc_sections)
        if not found_space:
            counties.append(None)
        
    df[store_name + "_county"] = counties

In [189]:
# https://gist.github.com/rogerallen/1583593
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}
# thank you to @kinghelix and @trevormarburger for this idea
abbrev_us_state = dict(map(reversed, us_state_abbrev.items()))


def get_state(df, store_name):
    states = []
    for i in range(len(df['store_location'])):
        address = df['store_location'][i]
        for abbrev in abbrev_us_state:
            if abbrev in address:
                states.append(abbrev_us_state[abbrev])
                break
        else:
            states.append(None)
            print(store_name)
            print(address)
        
    df[store_name + "_state"] = states

In [191]:
get_state(cabelas, "cabelas")
get_state(trader_joes, "trader_joes")
get_state(cinemarks, "cinemarks")
get_state(nordstroms, "nordstroms")

nordstroms
350 Walt Whitman Road Huntington Station, N11746
nordstroms
555 12th Street Northwest, Washington D.C. 20004

In [193]:
nordstroms['nordstroms_state'][nordstroms['nordstroms_state'].isna()] = ['New York', 'District of Columbia']

In [79]:
get_county(cabelas, "cabelas")

['Cabelas', '155', 'West 104th Avenue', 'Anchorage', 'Alaska', '99515', 'United States']
['3046', 'Mountain View Drive', 'Anchorage', 'Alaska', '99501', 'United States']
['Highway 6', 'Playmor Junction', 'South Slocan', 'Area H (The Slocan Valley)', 'Regional District of Central Kootenay', 'British Columbia', 'V0G 2G0', 'Canada']
["Cabela's", '7555', 'Southwest Nyberg Street', 'Tualatin', 'Metro', 'Oregon', '97062', 'United States']
['Buda', 'Texas', 'United States']
['Bass Pro Shops', '1972', 'Power Plant Parkway', 'Aberdeen Gardens', 'Hampton', 'Virginia', '23666', 'United States']
                                 store_location     cabelas_county
0     7090 Cabela Drive NW Huntsville, AL 35806     Madison County
1            5000 Bass Pro Blvd Leeds, AL 35094   Jefferson County
2      2553 Rocky Mount Rd Prattville, AL 36066      Elmore County
3      20000 Bass Pro Dr Spanish Fort, AL 36527     Baldwin County
4        155 W 104th Avenue Anchorage, AK 99515               None
..                                          ...                ...
148        1 Cabela Drive Triadelphia, WV 26059        Ohio County
149  1499 Lombardi Avenue Ashwaubenon, WI 54304       Brown County
150  33901 St Hwy 35 Prairie du Chien, WI 53821    Crawford County
151            1 Cabela Way Richfield, WI 53076  Washington County
152     1350 Cabela Drive Sun Prairie, WI 53590        Dane County

[153 rows x 2 columns]

In [81]:
get_county(cinemarks, "cinemarks")

['301', 'East 36th Avenue', 'Anchorage', 'Alaska', '99503', 'United States']
['Cinemark Movies 8', '1848', 'East Stop 13 Road', 'Indianapolis', 'Indiana', '46227', 'United States']
['Cinemark Century 16', '3200', 'Southwest Hocken Avenue', 'Central Beaverton', 'Beaverton', 'Metro', 'Oregon', '97005', 'United States']
['Happy Valley', 'Metro', 'Oregon', '97086', 'United States']
['Century 16', '4040', 'Southeast 82nd Avenue', 'Lents', 'Portland', 'Metro', 'Oregon', '97266', 'United States']
['Cinemark', '2413', 'Chesapeake Square Ring Road', 'Chesapeake Square Mall', 'Western Branch', 'Chesapeake', 'Virginia', '23321', 'United States']
['Cinemark City Center 12', '11810', 'Fountain Way', 'City Center', 'Newport News', 'Virginia', '23606', 'United States']
                                        store_location    cinemarks_county
0                 301 E. 36th Ave, Anchorage, AK 99503                None
1          370 The Bridge Street, Huntsville, AL 35806      Madison County
2                         17314 I-30, Benton, AR 72015       Saline County
3                  201 Skyline Drive, Conway, AR 72032     Faulkner County
4    18 Colonel Glenn Plaza Dr., Little Rock, AR 72210      Pulaski County
..                                                 ...                 ...
317                 5057 Main Street, Tacoma, WA 98407       Pierce County
318              1325 W. Poplar, Walla Walla, WA 99362  Walla Walla County
319                 7101 70th Court, Kenosha, WI 53142      Kenosha County
320                            Barboursville, WV 25504       Cabell County
321         2399 Meadowbrook Rd., Bridgeport, WV 26330     Harrison County

[322 rows x 2 columns]

In [117]:
get_county(nordstroms, "nordstroms")

['Bellevue', 'Rue de Bellevue', 'Romans-sur-Isère', 'Valence', 'Drôme', 'Auvergne-Rhône-Alpes', 'France métropolitaine', '26100', 'France']
['680', 'East Northern Lights Boulevard', 'Anchorage', 'Alaska', '99503', 'United States']
['Nordstrom', '701', 'Southwest Broadway', 'Downtown', 'Portland', 'Metro', 'Oregon', '97205', 'United States']
['Southeast Sunnyside & 128th', 'Southeast Sunnyside Road', 'Happy Valley', 'Metro', 'Oregon', '97015', 'United States']
['The Cheesecake Factory', '9700', 'Southwest Washington Square Road', 'Washington Square', 'North Tigard', 'Tigard', 'Metro', 'Oregon', '97223', 'United States']
['Evergreen Place Apartments', 'Five Oaks/Triple Creek', 'Beaverton', 'Metro', 'Oregon', 'United States']
['Nordstrom Rack', '245', 'Southwest Morrison Street', 'Downtown', 'Portland', 'Metro', 'Oregon', '97204', 'United States']
['Nordstrom Rack', '10159', 'Northeast Cascades Parkway', 'Portland', 'Metro', 'Oregon', '97220', 'United States']
['North Marine Drive', 'Rivergate Industrial District', 'Saint Johns', 'Portland', 'Metro', 'Oregon', '97203', 'United States']
['Nordstrom Rack', '9175', 'Southwest Cascade Avenue', 'Greenway', 'Beaverton', 'Metro', 'Oregon', '97008', 'United States']
['525', '9th Street Northwest', 'Penn Quarter', 'Washington', 'District of Columbia', '20004', 'United States']
['Indianapolis', 'Marion', 'Indiana', '46240', 'United States']
['Nordstrom Rack', '4036', 'East 82nd Street', 'Indianapolis', 'Indiana', '46250', 'United States']
['Chemin Saint-Lomard', 'Tavers', 'Orléans', 'Loiret', 'Centre-Val de Loire', 'France métropolitaine', '45190', 'France']
['V', 'Schmelzgasse', 'Afrikanerviertel', 'KG Leopoldstadt', 'Leopoldstadt', 'Wien', '1020', 'Österreich']
['Nordstrom Rack', '3967', 'Boston Street', 'Baltimore', 'Maryland', '21224', 'United States']
['Wisconsin', 'Elm Walk', 'Washington', 'District of Columbia', '20227', 'United States']
['1800', 'L Street Northwest', 'Golden Triangle', 'Washington', 'District of Columbia', '20036', 'United States']
['Crunch - Metro Center', '555', '12th Street Northwest', 'Downtown', 'Washington', 'District of Columbia', '20004', 'United States']
['The Fresh Market', '4588', 'Virginia Beach Boulevard', 'Pocahontas Village', 'Virginia Beach', 'Virginia', '23462', 'United States']
['5703', 'North Marine Drive', 'Rivergate Industrial District', 'Saint Johns', 'Portland', 'Metro', 'Oregon', '97203', 'United States']
                                        store_location      nordstroms_county
0                    500 Pine Street Seattle, WA 98101            King County
1         17200 Southcenter Parkway, Tukwila, WA 98188            King County
2               100 Bellevue Square Bellevue, WA 98004                   None
3               100 Southcenter Mall Tukwila, WA 98188            King County
4               4502 S Steele Street, Tacoma, WA 98409          Pierce County
..                                                 ...                    ...
364       7300 West Side Avenue North Bergen, NJ 07047          Hudson County
365         7700 18th Street SW Cedar Rapids, IA 52404            Linn County
366         839 Commerce Drive Upper Marlboro, MD20774                   None
367         5497 NE 49th Terrace Gainesville, FL 32609         Alachua County
368  17335 Glen Helen Parkway San Bernardino, CA 92407  San Bernardino County

[369 rows x 2 columns]

In [128]:
get_county(trader_joes, "trader_joes")

["Trader Joe's", '1101', '25th Street Northwest', 'West End', 'Washington', 'District of Columbia', '20037', 'United States']
["Trader Joe's", '1914', '14th Street Northwest', 'Logan Circle/Shaw', 'Washington', 'District of Columbia', '20009', 'United States']
['1240', '4th Street Northeast', 'Near Northeast', 'Washington', 'District of Columbia', '20002', 'United States']
["Trader Joe's", '750', 'Pennsylvania Avenue Southeast', 'Capitol Hill', 'Washington', 'District of Columbia', '20003', 'United States']
['WEST', '102', 'Rämistrasse', 'Hochschulen', 'Altstadt', 'Zürich', 'Bezirk Zürich', 'Zürich', '8091', 'Schweiz/Suisse/Svizzera/Svizra']
["Trader Joe's", '5473', 'East 82nd Street', 'Allisonville', 'Indianapolis', 'Indiana', '46250', 'United States']
["Trader Joe's", '2902', 'West 86th Street', 'Indianapolis', 'Indiana', '46268', 'United States']
['Carson City', 'Nevada', '89701-4763', 'United States']
["Trader Joe's", '11753', 'Southwest Beaverton Hillsdale Highway', 'Central Beaverton', 'Beaverton', 'Metro', 'Oregon', '97005', 'United States']
["Trader Joe's", '9345', 'Southeast 82nd Avenue', 'Battin', 'Happy Valley', 'Metro', 'Oregon', '97086', 'United States']
["Trader Joe's", '2285', 'Northwest 185th Avenue', 'Tanasbourne', 'East Hillsboro', 'Hillsboro', 'Metro', 'Oregon', '97124', 'United States']
['Southwest Bangy Road', 'Lake Forest', 'Lake Oswego', 'Metro', 'Oregon', '97035', 'United States']
['Southeast Steele & Cesar Chavez Boulevard', 'Southeast Steele Street', 'Reed', 'Portland', 'Metro', 'Oregon', '97202', 'United States']
['Northeast Glisan & 53rd', 'Northeast Glisan Street', 'North Tabor', 'Portland', 'Metro', 'Oregon', '97213-1422', 'United States']
["Trader Joe's", '4121', 'Northeast Halsey Street', 'Hollywood', 'Portland', 'Metro', 'Oregon', '97232', 'United States']
["Trader Joe's", '612', 'North Saint Asaph Street', 'Alexandria Historic District', 'Jefferson Houston', 'Alexandria', 'Virginia', '22314', 'United States']
['The V', '201-213', '15th Street Northwest', 'Venable', 'Starr Hill', 'Charlottesville', 'Virginia', '22903', 'United States']
['9464', 'Main Street', 'Green Acres', 'Fair Oaks', 'Fairfax', 'Fairfax (city)', 'Virginia', '22031', 'United States']
['Falls Church', 'Arlington', 'Virginia', 'United States']
['Trek Bicycle Newport News', '12551', 'Jefferson Avenue', 'Warwick Lawns', 'Newport News', 'Virginia', '23602', 'United States']
['Hilltop Plaza', 'Laurel Manor', 'Virginia Beach', 'Virginia', 'United States']
                                    store_location trader_joes_county
0            205 Summit Blvd, Birmingham, AL 35243   Jefferson County
1        4025 E Chandler Blvd, Ahwatukee, AZ 85048    Maricopa County
2               7720 W Bell Rd, Glendale, AZ 85308    Maricopa County
3               2050 E Baseline Rd, Mesa, AZ 85204    Maricopa County
4              4726 E Shea Blvd, Phoenix, AZ 85028    Maricopa County
..                                             ...                ...
477                 1700 Madison St, Vancouver, WA       Clark County
478         305 SE Chkalov Dr, Vancouver, WA 98683       Clark County
479     12665 W Bluemound Rd, Brookfield, WI 53005    Waukesha County
480  5600 N Port Washington Rd, Glendale, WI 53217   Milwaukee County
481              1810 Monroe St, Madison, WI 53711        Dane County

[482 rows x 2 columns]

In [131]:
tj_county_replacements = ['District of Columbia County', 'District of Columbia County', 'District of Columbia County',
                          'District of Columbia County', 'Lake County', 'Marion County', 'Marion County',
                         'Middlesex County', 'Douglas County', 'New York County', 'New York County',
                         'Washington County', 'Clackamas County', 'Washington County', 'Clackamas County',
                         'Multnomah County', 'Multnomah County', 'Multnomah County', 'City of Alexandria County',
                         'Albemarle County', 'Fairfax County', 'Fairfax County', 
                          'Newport News City', 'City of Virginia Beach County']

trader_joes['trader_joes_county'][trader_joes[pd.isna(trader_joes.trader_joes_county)].index] = tj_county_replacements

In [126]:
# https://www.geeksforgeeks.org/how-to-get-rows-index-names-in-pandas-dataframe/
nordstrom_replace_counties = ['King County', 'Anchorage County', 'Multnomah County', 'Clackamas County',
                             'Washington County', 'Washington County', 'Multnomah County', 'Multnomah County',
                             'Multnomah County', 'Washington County', 'El Paso County', 'District of Columbia County',
                             'Prince Georges County', 'Marion County', 'Marion County', 'DuPage County',
                             'Orange County', 'Los Angeles County', 'Suffolk County', 'New York County',
                             'Middlesex County', 'Middlesex County', 'Fairfax County', 'Baltimore City County',
                             'District of Columbia County', 'District of Columbia County', 'District of Columbia County',
                             'City of Virginia Beach County', 'Multnomah County', 'Prince Georges County']
nordstroms['nordstroms_county'][nordstroms[pd.isna(nordstroms.nordstroms_county)].index] = nordstrom_replace_counties

In [208]:
cinemarks['cinemarks_county'][0] = "Anchorage County"
cinemarks['cinemarks_county'][108] = "Marion County"
cinemarks['cinemarks_county'][192] = "Multnomah County"
cinemarks['cinemarks_county'][193] = "Clackamas County"
cinemarks['cinemarks_county'][195] = "Multnomah County"
cinemarks['cinemarks_county'][311] = "Chesapeake County"
cinemarks['cinemarks_county'][313] = "Newport News City"

In [209]:
# https://www.mapdevelopers.com/what-county-am-i-in.php
cabelas['cabelas_county'][4] = 'Anchorage County'
cabelas['cabelas_county'][5] = 'Anchorage County'
cabelas['cabelas_county'][16] = 'Mesa County'
cabelas['cabelas_county'][109] = 'Washington County'
cabelas['cabelas_county'][124] = 'Travis County'
cabelas['cabelas_county'][141] = 'Newport News City'

In [210]:
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == "newport news county"] = "newport news city"
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == "newport news county"] = "newport news city"

In [215]:
cabelas.to_csv("data/cabelas_counties.csv")
cinemarks.to_csv("data/cinemarks_counties.csv")
nordstroms.to_csv("data/nordstroms_counties.csv")
trader_joes.to_csv("data/trader_joes_counties.csv")

In [231]:
pres_results = pd.read_csv("data/county_level_presidential_results.csv")

In [ ]:
pres_results['county_name'][pres_results['state_name'] == "Alaska"] = "anchorage county"

In [171]:
set(sorted(pres_results.groupby('county_name').count()['state_name']))

# ensures that all of the county names are unique across states, which is not the case

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 23, 24, 25, 30}

In [235]:
# https://stackoverflow.com/questions/265960/best-way-to-strip-punctuation-from-a-string
pres_results['county_name'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in list(pres_results['county_name'])]
cabelas['cabelas_county'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in list(cabelas['cabelas_county'])]
cinemarks['cinemarks_county'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in list(cinemarks['cinemarks_county'])]
nordstroms['nordstroms_county'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in list(nordstroms['nordstroms_county'])]
trader_joes['trader_joes_county'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in list(trader_joes['trader_joes_county'])]
\

In [250]:
cabelas['cabelas_county'][cabelas.cabelas_county == 'saint charles county'] = 'st charles county'
cabelas['cabelas_county'][cabelas.cabelas_county == 'saint louis county'] = 'st louis county'

cinemarks['cinemarks_county'][cinemarks.cinemarks_county == 'saint joseph county'] = 'st joseph county'
cinemarks['cinemarks_county'][cinemarks.cinemarks_county == 'chesapeake county'] = 'chesapeake city'
cinemarks['cinemarks_county'][cinemarks.cinemarks_county == 'san francisco city and county'] = 'san francisco county'

nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'san francisco city and county'] = 'san francisco county'
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'saint louis county'] = 'st louis county'
nordstroms = nordstroms.drop([82])
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'district of columbia county'] = 'district of columbia'
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'city of virginia beach county'] = 'virginia beach city'
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'city and county of broomfield'] = 'broomfield county'
nordstroms['nordstroms_county'][nordstroms.nordstroms_county == 'baltimore city county'] = 'baltimore county'

trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'city of virginia beach county'] = 'virginia beach city'
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'district of columbia county'] = 'district of columbia'
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'saint louis county'] = 'st louis county'
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'san francisco city and county'] = 'san francisco county'
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'athensclarke county unified government'] = 'clarke county'
trader_joes['trader_joes_county'][trader_joes.trader_joes_county == 'city of alexandria county'] = 'alexandria city'

In [401]:
cabelas_merged = pd.merge(pres_results, cabelas, left_on=  ['county_name', 'state_name'],
                   right_on= ['cabelas_county', 'cabelas_state'], 
                   how = 'left')
cinemarks_merged = pd.merge(cabelas_merged, cinemarks, left_on=  ['county_name', 'state_name'],
                   right_on= ['cinemarks_county', 'cinemarks_state'], 
                   how = 'left')
nordstroms_merged = pd.merge(cinemarks_merged, nordstroms, left_on=  ['county_name', 'state_name'],
                   right_on= ['nordstroms_county', 'nordstroms_state'], 
                   how = 'left')
all_stores_merged = pd.merge(nordstroms_merged, trader_joes, left_on=  ['county_name', 'state_name'],
                   right_on= ['trader_joes_county', 'trader_joes_state'], 
                   how = 'left')

In [402]:
pres_results

     state_name  county_fips        county_name  votes_gop  votes_dem  total_votes   diff   per_gop   per_dem  per_point_diff
0       Alabama         1001     autauga county      19838       7503        27770  12335  0.714368  0.270184        0.444184
1       Alabama         1003     baldwin county      83544      24578       109679  58966  0.761714  0.224090        0.537623
2       Alabama         1005     barbour county       5622       4816        10518    806  0.534512  0.457882        0.076631
3       Alabama         1007        bibb county       7525       1986         9595   5539  0.784263  0.206983        0.577280
4       Alabama         1009      blount county      24711       2640        27588  22071  0.895716  0.095694        0.800022
...         ...          ...                ...        ...        ...          ...    ...       ...       ...             ...
3147    Wyoming        56037  sweetwater county      12229       3823        16603   8406  0.736554  0.230260        0.506294
3148    Wyoming        56039       teton county       4341       9848        14677  -5507  0.295769  0.670982       -0.375213
3149    Wyoming        56041       uinta county       7496       1591         9402   5905  0.797277  0.169219        0.628058
3150    Wyoming        56043    washakie county       3245        651         4012   2594  0.808824  0.162263        0.646560
3151    Wyoming        56045      weston county       3107        360         3542   2747  0.877188  0.101637        0.775551

[3152 rows x 10 columns]

In [403]:
all_stores_merged['cabelas'] = ~all_stores_merged['cabelas_county'].isna()
all_stores_merged['cinemark'] = ~all_stores_merged['cinemarks_county'].isna()
all_stores_merged['nordstrom'] = ~all_stores_merged['nordstroms_county'].isna()
all_stores_merged['trader_joes'] = ~all_stores_merged['trader_joes_county'].isna()

In [404]:
all_stores_merged = all_stores_merged.drop(columns = ['store_location_x', 'cabelas_county', 'cabelas_state', 'store_location_y', 'cinemarks_county', 'cinemarks_state', 'store_location_x', 'nordstroms_county', 'nordstroms_state', 'store_location_y', 'trader_joes_county', 'trader_joes_state'])

In [405]:
all_stores_merged = all_stores_merged.drop_duplicates(subset='county_fips')

In [406]:
all_stores_merged.to_csv("data/stores_with_pres_results.csv")

In [407]:
all_stores_merged

      state_name  county_fips        county_name  votes_gop  votes_dem  total_votes   diff   per_gop   per_dem  per_point_diff  cabelas  cinemark  nordstrom  trader_joes
0        Alabama         1001     autauga county      19838       7503        27770  12335  0.714368  0.270184        0.444184    False     False      False        False
1        Alabama         1003     baldwin county      83544      24578       109679  58966  0.761714  0.224090        0.537623     True     False      False        False
2        Alabama         1005     barbour county       5622       4816        10518    806  0.534512  0.457882        0.076631    False     False      False        False
3        Alabama         1007        bibb county       7525       1986         9595   5539  0.784263  0.206983        0.577280    False     False      False        False
4        Alabama         1009      blount county      24711       2640        27588  22071  0.895716  0.095694        0.800022    False     False      False        False
...          ...          ...                ...        ...        ...          ...    ...       ...       ...             ...      ...       ...        ...          ...
18809    Wyoming        56037  sweetwater county      12229       3823        16603   8406  0.736554  0.230260        0.506294    False     False      False        False
18810    Wyoming        56039       teton county       4341       9848        14677  -5507  0.295769  0.670982       -0.375213    False     False      False        False
18811    Wyoming        56041       uinta county       7496       1591         9402   5905  0.797277  0.169219        0.628058    False     False      False        False
18812    Wyoming        56043    washakie county       3245        651         4012   2594  0.808824  0.162263        0.646560    False     False      False        False
18813    Wyoming        56045      weston county       3107        360         3542   2747  0.877188  0.101637        0.775551    False     False      False        False

[3152 rows x 14 columns]

In [408]:
all_stores_merged = pd.merge(all_stores_merged, pd.read_csv("data/Unemployment.csv"),left_on=  ['county_fips'],
                   right_on= ['fips_txt'], 
                   how = 'left')

all_stores_merged = all_stores_merged.drop(columns=['fips_txt', 'Stabr','area_name',
 'Rural_urban_continuum_code_2013',
 'Urban_influence_code_2013',
 'Civilian_labor_force_2000',
 'Employed_2000',
 'Unemployed_2000',
 'Unemployment_rate_2000',
 'Civilian_labor_force_2001',
 'Employed_2001',
 'Unemployed_2001',
 'Unemployment_rate_2001',
 'Civilian_labor_force_2002',
 'Employed_2002',
 'Unemployed_2002',
 'Unemployment_rate_2002',
 'Civilian_labor_force_2003',
 'Employed_2003',
 'Unemployed_2003',
 'Unemployment_rate_2003',
 'Civilian_labor_force_2004',
 'Employed_2004',
 'Unemployed_2004',
 'Unemployment_rate_2004',
 'Civilian_labor_force_2005',
 'Employed_2005',
 'Unemployed_2005',
 'Unemployment_rate_2005',
 'Civilian_labor_force_2006',
 'Employed_2006',
 'Unemployed_2006',
 'Unemployment_rate_2006',
 'Civilian_labor_force_2007',
 'Employed_2007',
 'Unemployed_2007',
 'Unemployment_rate_2007',
 'Civilian_labor_force_2008',
 'Employed_2008',
 'Unemployed_2008',
 'Unemployment_rate_2008',
 'Civilian_labor_force_2009',
 'Employed_2009',
 'Unemployed_2009',
 'Unemployment_rate_2009',
 'Civilian_labor_force_2010',
 'Employed_2010',
 'Unemployed_2010',
 'Unemployment_rate_2010',
 'Civilian_labor_force_2011',
 'Employed_2011',
 'Unemployed_2011',
 'Unemployment_rate_2011',
 'Civilian_labor_force_2012',
 'Employed_2012',
 'Unemployed_2012',
 'Unemployment_rate_2012',
 'Civilian_labor_force_2013',
 'Employed_2013',
 'Unemployed_2013',
 'Unemployment_rate_2013',
 'Civilian_labor_force_2014',
 'Employed_2014',
 'Unemployed_2014',
 'Unemployment_rate_2014',
 'Civilian_labor_force_2015',
 'Employed_2015',
 'Unemployed_2015',
 'Unemployment_rate_2015',
 'Civilian_labor_force_2016',
 'Employed_2016',
 'Unemployed_2016',
 'Unemployment_rate_2016',
 'Civilian_labor_force_2017',
 'Employed_2017',
 'Unemployed_2017',
 'Unemployment_rate_2017',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Civilian_labor_force_2019',
 'Employed_2019',
 'Unemployed_2019',
 'Med_HH_Income_Percent_of_State_Total_2019'])

In [409]:
population_info = pd.read_csv("data/cc-est2019-alldata.csv")

In [410]:
population_info = population_info[population_info.YEAR == 12].drop(columns = 
                                                                   ['SUMLEV', 'YEAR', 'STATE', 'COUNTY', 'AGEGRP'])

In [411]:
population_info = population_info.groupby(['STNAME', 'CTYNAME']).sum()

In [412]:
population_info.columns

Index(['TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE', 'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE', 'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE', 'H_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE', 'HTOM_FEMALE', 'HWAC_MALE', 'HWAC_FEMALE', 'HBAC_MALE', 'HBAC_FEMALE', 'HIAC_MALE', 'HIAC_FEMALE', 'HAAC_MALE', 'HAAC_FEMALE', 'HNAC_MALE', 'HNAC_FEMALE'], dtype='object')

In [413]:
population_info[['WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE', 'H_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE', 'HTOM_FEMALE', 'HWAC_MALE', 'HWAC_FEMALE', 'HBAC_MALE', 'HBAC_FEMALE', 'HIAC_MALE', 'HIAC_FEMALE', 'HAAC_MALE', 'HAAC_FEMALE', 'HNAC_MALE', 'HNAC_FEMALE']]

                           WA_MALE  WA_FEMALE  BA_MALE  BA_FEMALE  IA_MALE  IA_FEMALE  AA_MALE  AA_FEMALE  NA_MALE  NA_FEMALE  ...  HWAC_MALE  HWAC_FEMALE  HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  HAAC_FEMALE  HNAC_MALE  HNAC_FEMALE
STNAME  CTYNAME                                                                                                                ...
Alabama Autauga County       41756      43458    10474      12000      242        290      572        740       64         52  ...       1556         1374        178          186         80           54         30           38         32           22
        Baldwin County      189620     200776    18972      20214     1806       1678     1864       2896      148        160  ...      10288         9292        536          562        528          394        138          130        110           70
        Barbour County       12778      11490    12622      11190      206        134      110        122       68         36  ...       1018          816        126          100        122           52          2            0         28           16
        Bibb County          17532      16850     5882       3644      106        100       46         50       44          8  ...        582          506         64           38         12           30         10            2         34            6
        Blount County        54516      56308     1032        924      384        356      170        200       84         50  ...       5588         5032        152          116        134          132         36           42         68           42
...                            ...        ...      ...        ...      ...        ...      ...        ...      ...        ...  ...        ...          ...        ...          ...        ...          ...        ...          ...        ...          ...
Wyoming Sweetwater County    40892      38504      694        502      648        604      406        500       70         68  ...       6642         5994        166          146        424          392         66           72         32           18
        Teton County         23134      21436      202        142      212        204      286        504       40         26  ...       3556         3156         50           46        210          162         32           30         24           14
        Uinta County         19506      19048      154        150      270        314       76        124       34         28  ...       1680         1680         34           46        164          222          6           24         16            4
        Washakie County       7518       7236       50         38      126        150       50         78        8          4  ...       1024          978         14           18        108          118         14           16          8            4
        Weston County         6784       6124       64         32      156        106       68        166        4          0  ...        264          240         10           16         46           40         12            8          4            0

[3142 rows x 56 columns]

In [414]:
# TOT_POP, TOT_MALE, TOT_FEMALE, WA (white alone), BA (black alone), H (hispanic), AA (asian alone)
population_info['white_pop'] = population_info['NHWA_MALE'] + population_info['NHWA_FEMALE']
population_info['asian_pop'] = population_info['NHAA_MALE'] + population_info['NHAA_FEMALE']
population_info['black_pop'] = population_info['NHBA_MALE'] + population_info['NHBA_FEMALE']
population_info['hispanic_pop'] = population_info['H_MALE'] + population_info['H_FEMALE']
population_info['other_pop'] = population_info['TOT_POP'] - population_info['white_pop'] - population_info['asian_pop'] - population_info['black_pop'] - population_info['hispanic_pop']
population_info = population_info.drop(columns = ['IA_MALE', 'IA_FEMALE',  'NA_MALE', 'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 
                                'WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE', 'IAC_MALE', 
                                'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE', 'NAC_FEMALE', 
                                'NH_MALE', 'NH_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 
                                'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 
                                'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 
                                'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 
                                'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 
                                'NHNAC_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'H_MALE', 'H_FEMALE',
                                'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 
                                'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE', 'HTOM_FEMALE',
                                'HWAC_MALE', 'HWAC_FEMALE', 'HBAC_MALE', 'HBAC_FEMALE', 'HIAC_MALE',
                                'HIAC_FEMALE', 'HAAC_MALE', 'HAAC_FEMALE', 'HNAC_MALE', 'HNAC_FEMALE',
                                'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', "AA_MALE", 'AA_FEMALE']).reset_index()

In [415]:
# https://stackoverflow.com/questions/265960/best-way-to-strip-punctuation-from-a-string

population_info['CTYNAME'] = [i.lower().translate(str.maketrans('', '', string.punctuation)) for i in population_info['CTYNAME']]
population_info['CTYNAME'][1802] = "doña ana county"

In [416]:
# https://www.census.gov/data-tools/demo/saipe/#/?map_geoSelector=mhi_c&s_measures=mhi_snc&s_year=2019
economics = pd.read_csv('data/percent_poverty.csv')
economics = economics[['County ID' ,'All Ages in Poverty Percent', 'Median Household Income in Dollars']]

In [417]:
all_stores_merged = pd.merge(all_stores_merged, economics, left_on=  ['county_fips'],
                   right_on= ['County ID'], 
                   how = 'left')

In [421]:
all_stores_merged

     state_name  county_fips        county_name  votes_gop  votes_dem  total_votes   diff   per_gop   per_dem  per_point_diff  cabelas  cinemark  nordstrom  trader_joes  Metro_2013  Unemployment_rate_2019 Median_Household_Income_2019  All Ages in Poverty Percent Median Household Income in Dollars
0       Alabama         1001     autauga county      19838       7503        27770  12335  0.714368  0.270184        0.444184    False     False      False        False         1.0                     2.7                       58,233                         12.1                            $58,233
1       Alabama         1003     baldwin county      83544      24578       109679  58966  0.761714  0.224090        0.537623     True     False      False        False         1.0                     2.7                       59,871                         10.1                            $59,871
2       Alabama         1005     barbour county       5622       4816        10518    806  0.534512  0.457882        0.076631    False     False      False        False         0.0                     3.8                       35,972                         27.1                            $35,972
3       Alabama         1007        bibb county       7525       1986         9595   5539  0.784263  0.206983        0.577280    False     False      False        False         1.0                     3.1                       47,918                         20.3                            $47,918
4       Alabama         1009      blount county      24711       2640        27588  22071  0.895716  0.095694        0.800022    False     False      False        False         1.0                     2.7                       52,902                         16.3                            $52,902
...         ...          ...                ...        ...        ...          ...    ...       ...       ...             ...      ...       ...        ...          ...         ...                     ...                          ...                          ...                                ...
3147    Wyoming        56037  sweetwater county      12229       3823        16603   8406  0.736554  0.230260        0.506294    False     False      False        False         0.0                     3.9                       80,639                          8.3                            $80,639
3148    Wyoming        56039       teton county       4341       9848        14677  -5507  0.295769  0.670982       -0.375213    False     False      False        False         0.0                     2.7                       98,837                          6.0                            $98,837
3149    Wyoming        56041       uinta county       7496       1591         9402   5905  0.797277  0.169219        0.628058    False     False      False        False         0.0                     3.9                       70,756                          8.5                            $70,756
3150    Wyoming        56043    washakie county       3245        651         4012   2594  0.808824  0.162263        0.646560    False     False      False        False         0.0                     3.9                       55,122                         11.1                            $55,122
3151    Wyoming        56045      weston county       3107        360         3542   2747  0.877188  0.101637        0.775551    False     False      False        False         0.0                     2.9                       59,410                         10.5                            $59,410

[3152 rows x 19 columns]

In [422]:
all_stores_merged = pd.merge(all_stores_merged, population_info, left_on=  ['state_name', 'county_name'],
                   right_on= ['STNAME', 'CTYNAME'], 
                   how = 'left').drop(columns = ["STNAME", "CTYNAME", 'County ID'])

In [425]:
all_stores_merged = all_stores_merged.rename(columns = {'TOT_POP': "total_pop", 'TOT_MALE': 'male_pop', 'TOT_FEMALE': 'female_pop',
                                    'All Ages in Poverty Percent': 'percent_poverty',
                                    'Median Household Income in Dollars': 'median_income'})

In [426]:
all_stores_merged.to_csv("data/all_stores_econ_and_populations.csv")

In [446]:
# https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/
education = pd.read_csv("data/education.csv")
education = education[['FIPS Code', "Percent of adults completing some college or associate's degree, 2015-19",
          "Percent of adults with a bachelor's degree or higher, 2015-19"]]
education["percent_educated"] = education["Percent of adults completing some college or associate's degree, 2015-19"]+education["Percent of adults with a bachelor's degree or higher, 2015-19"]
education = education.drop(columns = ["Percent of adults completing some college or associate's degree, 2015-19",
          "Percent of adults with a bachelor's degree or higher, 2015-19"])

all_stores_merged = pd.merge(all_stores_merged, education, left_on=  ['county_fips'],
                   right_on= ['FIPS Code'], 
                   how = 'left').drop(columns = ["FIPS Code"])

In [471]:
all_stores_merged['median_income'][all_stores_merged['median_income'].isna()] = '0'
all_stores_merged['median_income'] = [i.translate(str.maketrans('', '', string.punctuation)) for i in list(all_stores_merged['median_income'])]
all_stores_merged['median_income'][all_stores_merged['median_income'] == 0] = None

/opt/anaconda3/envs/sta440/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/envs/sta440/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [473]:
all_stores_merged.to_csv("data/final_data.csv")

In [472]:
all_stores_merged

     state_name  county_fips        county_name  votes_gop  votes_dem  total_votes   diff   per_gop   per_dem  per_point_diff  ...  median_income  total_pop  male_pop  female_pop  white_pop  asian_pop black_pop  hispanic_pop other_pop  percent_educated
0       Alabama         1001     autauga county      19838       7503        27770  12335  0.714368  0.270184        0.444184  ...          58233   111738.0   54184.0     57554.0    82430.0     1292.0   22196.0        3342.0    2478.0              55.0
1       Alabama         1003     baldwin county      83544      24578       109679  58966  0.761714  0.224090        0.537623  ...          59871   446468.0  216494.0    229974.0   371494.0     4692.0   38430.0       21068.0   10784.0              63.2
2       Alabama         1005     barbour county       5622       4816        10518    806  0.534512  0.457882        0.076631  ...          35972    49372.0   26128.0     23244.0    22470.0      232.0   23614.0        2234.0     822.0              37.6
3       Alabama         1007        bibb county       7525       1986         9595   5539  0.784263  0.206983        0.577280  ...          47918    44788.0   23858.0     20930.0    33326.0       92.0    9438.0        1246.0     686.0              34.2
4       Alabama         1009      blount county      24711       2640        27588  22071  0.895716  0.095694        0.800022  ...          52902   115652.0   56944.0     58708.0   100352.0      326.0    1744.0       11164.0    2066.0              47.1
...         ...          ...                ...        ...        ...          ...    ...       ...       ...             ...  ...            ...        ...       ...         ...        ...        ...       ...           ...       ...               ...
3147    Wyoming        56037  sweetwater county      12229       3823        16603   8406  0.736554  0.230260        0.506294  ...          80639    84686.0   43616.0     41070.0    67122.0      820.0    1004.0       13544.0    2196.0              59.7
3148    Wyoming        56039       teton county       4341       9848        14677  -5507  0.295769  0.670982       -0.375213  ...          98837    46928.0   24284.0     22644.0    38000.0      756.0     290.0        7108.0     774.0              80.3
3149    Wyoming        56041       uinta county       7496       1591         9402   5905  0.797277  0.169219        0.628058  ...          70756    40452.0   20448.0     20004.0    35314.0      184.0     252.0        3742.0     960.0              51.2
3150    Wyoming        56043    washakie county       3245        651         4012   2594  0.808824  0.162263        0.646560  ...          55122    15610.0    7926.0      7684.0    12834.0      110.0      76.0        2216.0     374.0              60.0
3151    Wyoming        56045      weston county       3107        360         3542   2747  0.877188  0.101637        0.775551  ...          59410    13854.0    7248.0      6606.0    12472.0      226.0      90.0         570.0     496.0              56.2

[3152 rows x 28 columns]